import 'dart:async';
import 'dart:convert';

import 'package:flutter/foundation.dart';
import 'package:flutter_reactive_ble/flutter_reactive_ble.dart';
import 'package:shared_preferences/shared_preferences.dart';

import 'ble_transport.dart';
import 'prototype_protocol.dart';
import 'prototype_store.dart';
import 'prototype_sync.dart';
import 'ble_access.dart';

class BleDeviceInfo {
  const BleDeviceInfo({
    required this.id,
    required this.name,
    required this.rssi,
  });
  final String id;
  final String name;
  final int rssi;
}

enum BleConnectionStatus {
  disconnected,
  scanning,
  connecting,
  subscribing,
  calibrating,
  ready,
  syncing,
  complete,
  error,
}

enum ClockCalibrationStatus {
  unavailable,
  unsupported,
  pending,
  synced,
  failed,
}

/// B's scan/reconnect flow with durable text sync. Owned above navigation, so
/// browsing A's history does not cancel Bluetooth or switch its storage target.
class BleService extends ChangeNotifier {
  BleService({
    BleTransport? transport,
    PrototypeStore? store,
    this.usePreferences = true,
    this.handshakeInterval = const Duration(seconds: 1),
    this.reconnectDelay = const Duration(seconds: 2),
    this.clockRetryInterval = const Duration(seconds: 2),
    DateTime Function()? clock,
  }) : _transportOverride = transport,
       _clock = clock ?? DateTime.now,
       _store = store; // ignore: prefer_initializing_formals
  factory BleService.test() => BleService(usePreferences: false);
  final BleTransport? _transportOverride;
  BleTransport? _defaultTransport;
  BleTransport get _transport =>
      _transportOverride ?? (_defaultTransport ??= ReactiveBleTransport());
  PrototypeStore? _store;
  Future<PrototypeStore>? _openingStore;
  Future<void> Function(DateTime)? _recordSyncCompleted;

  /// Install the diary destination before scanning. This also upgrades every
  /// retained timestamp from older APKs, including records beyond the UI's 100.
  Future<void> attachRecordSink({
    required Future<void> Function(PrototypeRecord) save,
    required Future<void> Function(DateTime) markSyncCompleted,
  }) async {
    if (_sync != null) {
      throw StateError('Cannot change storage during synchronization');
    }
    final existing = await _getStore();
    final raw = existing is RecordingPrototypeStore
        ? existing.rawStore
        : existing;
    final recording = RecordingPrototypeStore(raw, save);
    await recording.backfill();
    _store = recording;
    _recordSyncCompleted = markSyncCompleted;
  }

  Future<PrototypeStore> _getStore() => _store != null
      ? Future.value(_store!)
      : (_openingStore ??= SqlitePrototypeStore.open()
            .then((store) {
              _store = store;
              return store;
            })
            .catchError((Object error) {
              _openingStore = null;
              throw error;
            }));
  final bool usePreferences;
  final Duration handshakeInterval;
  final Duration reconnectDelay;
  final Duration clockRetryInterval;
  final DateTime Function() _clock;
  static const maxReconnectAttempts = 3;
  static const serviceUuid = prototypeServiceUuid;
  static const notifyCharacteristicUuid = prototypeCharacteristicUuid;
  BleConnectionStatus status = BleConnectionStatus.disconnected;
  final List<BleDeviceInfo> _devices = [];
  final List<String> _logs = [];
  final List<String> _rawLines = [];
  List<PrototypeRecord> savedRecords = [];
  List<BleDeviceInfo> get devices => List.unmodifiable(_devices);
  List<String> get logs => List.unmodifiable(_logs);
  List<String> get rawLines => List.unmodifiable(_rawLines);
  String? connectedDeviceId;
  String? _lastDeviceId;
  String? stableDeviceId;
  bool autoReconnectEnabled = true;
  bool autoScanEnabled = false;
  bool _suppressed = false;
  bool _disposed = false;
  bool _foreground = true;
  String? _resumeDeviceId;
  bool _resumeScan = false;
  Future<void> _lifecycle = Future.value();
  bool get foreground => _foreground;
  bool needsPermissionSettings = false;
  bool _initialized = false;
  bool _linkConnected = false;
  int _epoch = 0;
  int _scanEpoch = 0;
  int _retryCount = 0;
  int receivedBytes = 0;
  String lastHex = '';
  String? lastError;
  int syncedCount = 0;
  int _commitRetries = 0;
  PrototypeSync? _sync;
  /// Device-initiated transfer request. The device owns sync initiation now:
  /// after clock calibration, and after every button record, it offers
  /// `REQ|token|count`. The app replies `SYNC_REQ|token` to consent. The token
  /// is generated by the device and reused for START/ACK/COMMIT. A null value
  /// means no outstanding offer; `_wantsSync` records a user tap on "Re-sync"
  /// so the next REQ is accepted automatically.
  String? _deviceRequestToken;
  int? _deviceRequestCount;
  bool _wantsSync = false;
  bool supportsClockCalibration = false;
  ClockCalibrationStatus clockStatus = ClockCalibrationStatus.unavailable;
  DateTime? lastClockCalibrationAt;
  String? _clockCommand;
  int _clockAttempts = 0;
  bool get canCalibrateClock =>
      _linkConnected &&
      stableDeviceId != null &&
      supportsClockCalibration &&
      _sync == null &&
      clockStatus != ClockCalibrationStatus.pending &&
      status != BleConnectionStatus.syncing;
  String get clockStatusLabel => switch (clockStatus) {
    ClockCalibrationStatus.unavailable =>
      'Device clock: checked after connection',
    ClockCalibrationStatus.unsupported =>
      'Device clock: phone calibration is unsupported by this firmware',
    ClockCalibrationStatus.pending => 'Device clock: calibrating from phone',
    ClockCalibrationStatus.synced =>
      'Device clock: calibrated from phone UTC; shown in your timezone',
    ClockCalibrationStatus.failed => 'Device clock: calibration failed; retry',
  };
  bool get hasConnection => connectedDeviceId != null;
  /// The link is ready to sync. The device drives initiation, so this only
  /// means the handshake, clock and session state permit an offer to be
  /// accepted; it does not mean the device has offered one yet.
  bool get canSync =>
      _linkConnected &&
      stableDeviceId != null &&
      clockStatus != ClockCalibrationStatus.pending &&
      (!supportsClockCalibration ||
          clockStatus == ClockCalibrationStatus.synced) &&
      _sync == null &&
      status != BleConnectionStatus.syncing;
  /// True when the device has offered a transfer that the app has not accepted.
  bool get hasPendingDeviceRequest => _deviceRequestToken != null;
  /// File count the device announced in its outstanding REQ, if any.
  int? get pendingDeviceRequestCount => _deviceRequestCount;
  /// True after the user tapped "Re-sync" while no offer was on the table; the
  /// next REQ from the device is accepted and this flag clears.
  bool get waitingForDeviceRequest => _wantsSync;
  String get statusLabel => switch (status) {
    BleConnectionStatus.disconnected => 'Disconnected',
    BleConnectionStatus.scanning => 'Scanning',
    BleConnectionStatus.connecting => 'Connecting',
    BleConnectionStatus.subscribing => 'Connected; waiting for handshake',
    BleConnectionStatus.calibrating => 'Calibrating device clock',
    BleConnectionStatus.ready =>
      _wantsSync
          ? 'Ready; waiting for the device to offer records'
          : 'Ready',
    BleConnectionStatus.syncing => 'Receiving and saving',
    BleConnectionStatus.complete => 'Records saved',
    BleConnectionStatus.error => 'Needs attention',
  };
  StreamSubscription<DiscoveredDevice>? _scan;
  StreamSubscription<ConnectionStateUpdate>? _connection;
  StreamSubscription<List<int>>? _notify;
  Timer? _reconnectTimer;
  Timer? _scanTimer;
  Timer? _handshakeTimer;
  Timer? _syncTimer;
  Timer? _clockTimer;
  DateTime? _lastScanStopped;
  final _buffer = PrototypeLineBuffer();
  Future<void> _incoming = Future.value();
  Future<void> _outgoing = Future.value();

  bool _active(int epoch) => !_disposed && epoch == _epoch;
  void _changed() {
    if (!_disposed) notifyListeners();
  }

  void _log(String message) {
    if (_disposed) return;
    _logs.add('${DateTime.now().toIso8601String().substring(11, 19)} $message');
    if (_logs.length > 80) _logs.removeAt(0);
    _changed();
  }

  void _state(BleConnectionStatus value) {
    status = value;
    _changed();
  }

  void _fail(Object error) {
    if (_disposed) return;
    _handshakeTimer?.cancel();
    _syncTimer?.cancel();
    _clockTimer?.cancel();
    _clockCommand = null;
    if (clockStatus == ClockCalibrationStatus.pending) {
      clockStatus = ClockCalibrationStatus.failed;
    }
    _sync = null;
    // The failed offer is not consumable any more; accept the device's next REQ
    // instead of treating it as a duplicate and going silent.
    _deviceRequestToken = null;
    _deviceRequestCount = null;
    lastError = '$error';
    needsPermissionSettings =
        error is BleAccessException && error.canOpenSettings;
    _log('$error');
    _state(BleConnectionStatus.error);
  }

  Future<void> initializeAutoScan() async {
    if (_initialized || _disposed) return;
    _initialized = true;
    try {
      if (usePreferences) {
        final prefs = await SharedPreferences.getInstance();
        if (_disposed) return;
        _lastDeviceId = prefs.getString('ble.last_device_id');
        autoScanEnabled = prefs.getBool('ble.auto_scan_enabled') ?? false;
      }
      if (usePreferences || _store != null) {
        await _getStore();
        if (_disposed) {
          return;
        }
        savedRecords = await _store!.readRecent();
      }
      _changed();
      if (autoScanEnabled && !_suppressed && !_disposed) await startScan();
    } catch (error) {
      _fail(error);
    }
  }

  void setAutoReconnect(bool value) {
    autoReconnectEnabled = value;
    if (!value) _reconnectTimer?.cancel();
    _changed();
  }

  Future<void> setAutoScan(bool value) async {
    autoScanEnabled = value;
    _changed();
    try {
      if (usePreferences) {
        final prefs = await SharedPreferences.getInstance();
        await prefs.setBool('ble.auto_scan_enabled', value);
      }
      if (_disposed) return;
      if (value && !hasConnection) {
        await startScan();
      } else if (!value) {
        await cancelScan();
      }
    } catch (error) {
      _fail(error);
    }
  }

  Future<void> _stopScan() async {
    _scanEpoch++;
    _scanTimer?.cancel();
    final subscription = _scan;
    _scan = null;
    if (subscription != null) {
      await subscription.cancel();
      _lastScanStopped = DateTime.now();
    }
  }

  Future<void> startScan() async {
    if (_disposed ||
        !_foreground ||
        hasConnection ||
        status == BleConnectionStatus.scanning) {
      return;
    }
    _suppressed = false;
    _reconnectTimer?.cancel();
    await _stopScan();
    final scanEpoch = _scanEpoch;
    _state(BleConnectionStatus.scanning);
    lastError = null;
    try {
      await _transport.ensureReady();
      if (_lastScanStopped != null) {
        final remaining =
            const Duration(seconds: 2) -
            DateTime.now().difference(_lastScanStopped!);
        if (remaining > Duration.zero) await Future<void>.delayed(remaining);
      }
      if (_disposed || _suppressed || scanEpoch != _scanEpoch) return;
      _devices.clear();
      _scan = _transport.scan().listen(
        (device) {
          if (_disposed || scanEpoch != _scanEpoch) return;
          final info = BleDeviceInfo(
            id: device.id,
            name: device.name.isEmpty ? 'ESP32 device' : device.name,
            rssi: device.rssi,
          );
          final index = _devices.indexWhere((d) => d.id == info.id);
          if (index < 0) {
            _devices.add(info);
          } else {
            _devices[index] = info;
          }
          _changed();
          if (autoScanEnabled && device.id == _lastDeviceId && !hasConnection) {
            unawaited(connectToDevice(device.id));
          }
        },
        onError: (Object error) {
          if (scanEpoch != _scanEpoch || _disposed) return;
          unawaited(_stopScan());
          _fail(error);
        },
      );
      _scanTimer = Timer(const Duration(seconds: 15), () {
        if (scanEpoch == _scanEpoch && !_disposed) unawaited(cancelScan());
      });
    } catch (error) {
      if (scanEpoch == _scanEpoch) _fail(error);
    }
  }

  Future<void> cancelScan() async {
    _resumeDeviceId = null;
    _resumeScan = false;
    _suppressed = true;
    _reconnectTimer?.cancel();
    await _stopScan();
    if (!hasConnection) _state(BleConnectionStatus.disconnected);
  }

  Future<void> connectToDevice(
    String deviceId, {
    bool resetRetryCount = true,
  }) async {
    if (_disposed || !_foreground) return;
    _suppressed = false;
    _reconnectTimer?.cancel();
    final epoch = ++_epoch;
    if (resetRetryCount) _retryCount = 0;
    connectedDeviceId = deviceId;
    stableDeviceId = null;
    lastError = null;
    _state(BleConnectionStatus.connecting);
    try {
      await _stopScan();
      await _clearLink();
      if (!_active(epoch)) return;
      await _transport.ensureReady();
      if (!_active(epoch)) return;
      _connection = _transport
          .connect(deviceId)
          .listen(
            (update) {
              if (!_active(epoch)) return;
              switch (update.connectionState) {
                case DeviceConnectionState.connected:
                  if (!_linkConnected) {
                    _linkConnected = true;
                    unawaited(_subscribe(deviceId, epoch));
                  }
                case DeviceConnectionState.disconnected:
                  unawaited(_linkLost(deviceId, epoch, update.failure));
                case DeviceConnectionState.connecting:
                  _state(BleConnectionStatus.connecting);
                case DeviceConnectionState.disconnecting:
                  break;
              }
            },
            onError: (Object error) {
              unawaited(_linkLost(deviceId, epoch, error));
            },
          );
    } catch (error) {
      await _linkLost(deviceId, epoch, error);
    }
  }

  Future<void> _subscribe(String deviceId, int epoch) async {
    try {
      _state(BleConnectionStatus.subscribing);
      await _transport.discover(deviceId);
      if (!_active(epoch)) return;
      _log(
        'Services discovered. Subscribing to notifications and waiting for READY.',
      );
      _notify = _transport
          .subscribe(deviceId)
          .listen(
            (bytes) {
              if (!_active(epoch)) return;
              receivedBytes += bytes.length;
              lastHex = bytes
                  .map((b) => b.toRadixString(16).padLeft(2, '0'))
                  .join(' ');
              for (final line in _buffer.add(bytes)) {
                _incoming = _incoming
                    .then((_) async {
                      if (_active(epoch)) await _receive(line, epoch);
                    })
                    .catchError((Object error) {
                      if (_active(epoch)) _fail(error);
                    });
              }
              _changed();
            },
            onError: (Object error) {
              if (_active(epoch)) _fail(error);
            },
          );
      var attempts = 0;
      Future<void> hello() async {
        if (!_active(epoch) ||
            stableDeviceId != null ||
            status != BleConnectionStatus.subscribing) {
          return;
        }
        if (++attempts > 6) {
          _fail(
            'No READY reply. Use the matching firmware. Received legacy text is shown below.',
          );
          return;
        }
        try {
          await _write('HELLO', epoch);
          if (_active(epoch) &&
              stableDeviceId == null &&
              status == BleConnectionStatus.subscribing) {
            _handshakeTimer = Timer(
              handshakeInterval,
              () => unawaited(hello()),
            );
          }
        } catch (error) {
          if (_active(epoch)) _fail(error);
        }
      }

      await hello();
    } catch (error) {
      if (_active(epoch)) _fail(error);
    }
  }

  Future<void> _write(String command, int epoch, {bool Function()? guard}) {
    final bytes = utf8.encode(command);
    if (bytes.length > 20) {
      throw ArgumentError('Control command exceeds 20 bytes');
    }
    final pending = _outgoing.then((_) async {
      if (!_active(epoch) || !_linkConnected) {
        throw StateError('Connection changed; stale command cancelled');
      }
      if (guard != null && !guard()) return;
      await _transport.write(connectedDeviceId!, bytes);
      if (_active(epoch)) _log('Sending $command');
    });
    _outgoing = pending.catchError((Object _) {});
    return pending;
  }

  Future<void> _receive(String line, int epoch) async {
    _rawLines.add(line);
    if (_rawLines.length > 40) _rawLines.removeAt(0);
    List<String> fields;
    try {
      fields = decodePrototypeFrame(line);
    } on FormatException catch (error) {
      _log(error.message);
      return;
    }
    if (fields[0] == 'READY') {
      if (status != BleConnectionStatus.subscribing) return;
      if ((fields.length != 3 && fields.length != 4) ||
          fields[2] != 'P01' ||
          (fields.length == 4 && fields[3] != 'TIME1') ||
          !RegExp(r'^[0-9A-Fa-f]{12}$').hasMatch(fields[1])) {
        throw const FormatException(
          'READY format or protocol version does not match',
        );
      }
      if (stableDeviceId != null) return;
      _handshakeTimer?.cancel();
      stableDeviceId = fields[1].toUpperCase();
      supportsClockCalibration = fields.length == 4;
      clockStatus = supportsClockCalibration
          ? ClockCalibrationStatus.unavailable
          : ClockCalibrationStatus.unsupported;
      _lastDeviceId = connectedDeviceId;
      _state(BleConnectionStatus.ready);
      _log(
        'READY received: notifications confirmed for device $stableDeviceId',
      );
      if (usePreferences) {
        final prefs = await SharedPreferences.getInstance();
        if (!_active(epoch)) return;
        await prefs.setString('ble.last_device_id', _lastDeviceId!);
      }
      if (_active(epoch)) {
        if (supportsClockCalibration) {
          // Only wait for the write here. Waiting for TOK would block the
          // serialized notification queue that must deliver that acknowledgment.
          await requestClockCalibration();
        } else {
          _log(
            'Legacy P01 firmware has no TIME1; timestamps have not been calibrated by the phone.',
          );
          // The device offers REQ right after READY; do not request sync here.
        }
      }
      return;
    }
    if (fields[0] == 'TOK') {
      if (clockStatus != ClockCalibrationStatus.pending ||
          fields.length != 2 ||
          _clockCommand?.substring(3) != fields[1]) {
        return;
      }
      _clockTimer?.cancel();
      _clockCommand = null;
      clockStatus = ClockCalibrationStatus.synced;
      lastClockCalibrationAt = _clock();
      lastError = null;
      _state(BleConnectionStatus.ready);
      _log(
        'Clock calibration confirmed. Existing file times remain unchanged.',
      );
      // The device now offers `REQ|token|count`; _receive answers it. No app
      // request is issued here, so a calibration-only retry cannot start a
      // transfer on its own.
      return;
    }
    if (fields[0] == 'REQ') {
      if (fields.length != 3 || !RegExp(r'^[0-9A-Fa-f]{8}$').hasMatch(fields[1])) {
        throw const FormatException('Invalid REQ frame');
      }
      final count = int.tryParse(fields[2]);
      if (count == null || count < 0 || count > 256) {
        throw const FormatException('REQ count out of range');
      }
      if (!canSync || _deviceRequestToken != null) {
        // Ignore a duplicate offer, an offer before calibration, or one that
        // arrives while a session is already running. The device retries the
        // same token, so nothing is lost.
        _log('Ignored device REQ (session not ready or already offered)');
        return;
      }
      _deviceRequestToken = fields[1];
      _deviceRequestCount = count;
      _log('Device offered $count record(s); accepting');
      _changed();
      // Accept immediately: the device is the initiator, so a valid offer is
      // always consented to once the session is ready. `_wantsSync` only
      // documents the user's earlier tap and needs no separate branch.
      _wantsSync = false;
      await _acceptDeviceRequest(epoch);
      return;
    }
    if (fields[0] == 'TER') {
      if (clockStatus == ClockCalibrationStatus.pending && fields.length == 2) {
        _fail(
          'Device clock calibration failed (${fields[1]}). Check firmware/NVS and tap Calibrate clock.',
        );
      }
      return;
    }
    final sync = _sync;
    if (sync == null || fields.length < 2 || fields[1] != sync.token) return;
    await sync.accept(fields);
    if (!_active(epoch) || !identical(_sync, sync)) return;
    syncedCount = sync.savedCount;
    if (sync.completed) {
      _syncTimer?.cancel();
      savedRecords = await _store!.readRecent();
      if (!_active(epoch)) return;
      await _recordSyncCompleted?.call(_clock());
      if (!_active(epoch)) return;
      _sync = null;
      // The round is finished; a later button press or reconnect produces a
      // brand-new REQ with a fresh token.
      _deviceRequestToken = null;
      _deviceRequestCount = null;
      _retryCount = 0;
      _state(BleConnectionStatus.complete);
      _log(
        'Saved $syncedCount device records. The device archived the transferred files.',
      );
    } else {
      _armSyncTimeout(epoch);
      _changed();
    }
  }

  Future<void> requestClockCalibration() async {
    if (_disposed || !_foreground || !canCalibrateClock) return;
    final now = _clock();
    final utc = now.millisecondsSinceEpoch ~/ 1000;
    // The device stores and reports UTC only. The phone's timezone offset is
    // applied locally when displaying device timestamps, never sent on the wire.
    if (utc < 946684800 || utc > 4102444799) {
      clockStatus = ClockCalibrationStatus.failed;
      _fail(
        'Phone date is out of range (2001–2099). Check system time.',
      );
      return;
    }
    final command = 'TM|${utc.toRadixString(16).padLeft(16, '0')}';
    _clockCommand = command;
    _clockAttempts = 0;
    clockStatus = ClockCalibrationStatus.pending;
    lastClockCalibrationAt = null;
    lastError = null;
    _state(BleConnectionStatus.calibrating);
    await _sendClock(command, _epoch);
  }

  Future<void> _sendClock(String command, int epoch) async {
    if (!_active(epoch) || _clockCommand != command) return;
    if (_clockAttempts++ >= 3) {
      _fail(
        'Device clock calibration timed out. Files are retained; tap Calibrate clock to retry.',
      );
      return;
    }
    try {
      await _write(command, epoch, guard: () => _clockCommand == command);
      if (_active(epoch) && _clockCommand == command) {
        _clockTimer?.cancel();
        _clockTimer = Timer(
          clockRetryInterval,
          () => unawaited(_sendClock(command, epoch)),
        );
      }
    } catch (error) {
      if (_active(epoch)) _fail(error);
    }
  }

  /// User-facing "Re-sync". The device initiates transfers, so this either
  /// accepts an offer already on the table or arms `_wantsSync` so the next
  /// REQ is accepted automatically. It never invents a token: only the device
  /// may start a round, which keeps START/ACK/COMMIT on one shared session id.
  Future<void> requestSync() async {
    if (_disposed || !_foreground || !canSync) return;
    if (_deviceRequestToken == null) {
      _wantsSync = true;
      _log('Waiting for the device to offer its next transfer');
      _changed();
      return;
    }
    await _acceptDeviceRequest(_epoch);
  }

  /// Consents to the device's outstanding REQ and opens the shared token into a
  /// PrototypeSync. The device only sends BEGIN after seeing this SYNC_REQ, so
  /// the token in the reply must match its offer exactly.
  Future<void> _acceptDeviceRequest(int epoch) async {
    final token = _deviceRequestToken;
    if (token == null || !canSync) return;
    _state(BleConnectionStatus.syncing);
    lastError = null;
    syncedCount = 0;
    _commitRetries = 0;
    _wantsSync = false;
    try {
      await _getStore();
      if (!_active(epoch) || _deviceRequestToken != token) return;
      late final PrototypeSync sync;
      sync = PrototypeSync(
        deviceId: stableDeviceId!,
        token: token,
        store: _store!,
        write: (command) async {
          if (identical(_sync, sync)) {
            await _write(command, epoch, guard: () => identical(_sync, sync));
          }
        },
        isActive: () => _active(epoch) && identical(_sync, sync),
      );
      _sync = sync;
      await _write('SYNC_REQ|$token', epoch);
      if (_active(epoch)) _armSyncTimeout(epoch);
    } catch (error) {
      if (_active(epoch)) _fail(error);
    }
  }

  void _armSyncTimeout(int epoch) {
    _syncTimer?.cancel();
    final committing = _sync?.endReceived == true;
    _syncTimer = Timer(Duration(seconds: committing ? 2 : 12), () async {
      if (!_active(epoch)) return;
      if (_sync?.endReceived == true && _commitRetries++ < 3) {
        try {
          await _write('COMMIT|${_sync!.token}', epoch);
          if (_active(epoch) && _sync != null) _armSyncTimeout(epoch);
        } catch (error) {
          if (_active(epoch)) _fail(error);
        }
      } else {
        _fail(
          'Sync timed out. Saved records are retained; tap Re-sync to retry.',
        );
      }
    });
  }

  Future<void> _linkLost(String deviceId, int epoch, Object? error) async {
    if (!_active(epoch)) return;
    final lostEpoch = ++_epoch;
    connectedDeviceId = null;
    stableDeviceId = null;
    await _clearLink();
    if (!_active(lostEpoch)) return;
    if (error != null) {
      _fail(error);
    } else {
      _state(BleConnectionStatus.disconnected);
    }
    _log('Connection interrupted. Unfinished records are not acknowledged.');
    if (autoReconnectEnabled &&
        !_suppressed &&
        _retryCount < maxReconnectAttempts) {
      _retryCount++;
      _log(
        'Reconnecting in ${reconnectDelay.inSeconds} s ($_retryCount/$maxReconnectAttempts)',
      );
      _reconnectTimer = Timer(reconnectDelay, () {
    // A device offer belongs to one link; the device re-offers after reconnect.
    _deviceRequestToken = null;
    _deviceRequestCount = null;
    _wantsSync = false;
        if (_active(lostEpoch) && !_suppressed && autoReconnectEnabled) {
          unawaited(connectToDevice(deviceId, resetRetryCount: false));
        }
      });
    }
  }

  Future<void> _clearLink() async {
    _handshakeTimer?.cancel();
    _syncTimer?.cancel();
    _clockTimer?.cancel();
    _clockCommand = null;
    supportsClockCalibration = false;
    clockStatus = ClockCalibrationStatus.unavailable;
    lastClockCalibrationAt = null;
    _linkConnected = false;
    _sync = null;
    // A dropped link invalidates the device's outstanding offer. Leaving the
    // stale token here makes the next REQ look like a duplicate, so the app
    // would silently ignore it and the device would retry forever.
    _deviceRequestToken = null;
    _deviceRequestCount = null;
    _wantsSync = false;
    _buffer.reset();
    final notify = _notify;
    final connection = _connection;
    _notify = null;
    _connection = null;
    await notify?.cancel();
    await connection?.cancel();
  }

  Future<void> disconnect() async {
    _resumeDeviceId = null;
    _resumeScan = false;
    await _disconnectLink();
  }

  Future<void> _disconnectLink() async {
    _suppressed = true;
    ++_epoch;
    _reconnectTimer?.cancel();
    await _stopScan();
    await _clearLink();
    connectedDeviceId = null;
    stableDeviceId = null;
    _state(BleConnectionStatus.disconnected);
  }

  /// Foreground-only BLE on both mobile platforms. Ignore `inactive` (permission
  /// dialogs / Control Center); pause only on the application's `paused` event.
  Future<void> setForeground(bool value) {
    Future<void> restoration = Future.value();
    _lifecycle = _lifecycle
        .then((_) async {
          if (_disposed || _foreground == value) return;
          _foreground = value;
          if (!value) {
            _resumeDeviceId = autoReconnectEnabled ? connectedDeviceId : null;
            _resumeScan = status == BleConnectionStatus.scanning;
            await _disconnectLink();
            _log(
              'App in background. Bluetooth paused; saved records retained.',
            );
          } else {
            final device = _resumeDeviceId;
            final scan = _resumeScan;
            _resumeDeviceId = null;
            _resumeScan = false;
            if (device != null && autoReconnectEnabled) {
              restoration = connectToDevice(device);
            } else if (scan) {
              restoration = startScan();
            }
          }
          _changed();
        })
        .catchError((Object error) {
          _fail(error);
        });
    // Permission prompts can remain open. A later pause must be able to cancel
    // this restoration without waiting for the prompt or scan cooldown.
    return _lifecycle.then((_) => restoration);
  }

  Future<void> _close() async {
    await disconnect();
    await _incoming;
    await _outgoing;
    try {
      await _openingStore;
    } catch (_) {
      /* Opening failed: no handle to close. */
    }
    await _store?.close();
  }

  @override
  void dispose() {
    _disposed = true;
    unawaited(_close());
    super.dispose();
  }
}
